#%RAML 1.0
title: max-the-mule-broker-api
baseUri: http://localhost:8081/{version}
version: v1
 
/orders:
  get:
    description: Retrieve all the orders data
    queryParameters:
      status: 
        type: Status
        required: false
      net-value:
        type: boolean
        required: false
    responses:
      200:
        body:
          application/json:
            type: Order[]
  post:
    description: Creates a pending order set with the BUY action.
    body: 
      application/json:
        type: BaseOrder
    is: [responseMessage]

traits: 
  responseMessage:
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
                "message":"<<resourcePathName>> order created"
              }        
        
types:
  Order:
    type: BaseOrder
    properties:
      ACTION: Action
      ORDER_DATE: datetime-only
      STATUS: Status
      TX_NUMBER: number
    example:
      ACTION: buy
      PRICE: "205.21"
      ORDER_DATE: "2015-12-28T15:06:25"
      STATUS: filled
      TX_NUMBER: 1
      QUANTITY: 50
      SYMBOL: SPY
      
  BaseOrder:
    type: object
    properties:
      PRICE: string
      QUANTITY: number
      SYMBOL: string
    example:
      PRICE: "205.21"
      QUANTITY: 50
      SYMBOL: SPY
          
  Action:
    type: string
    enum: [buy, sell]
    
  Status:
    type: string
    enum: [canceled, filled, pending]  